TRANSFORMERS:
  active_pairs: Activity
  espsim: Electrostatic
  shapesim: Shape
  tanimoto: Fingerprint

NUM_POINTS:
  LOW: 1000
  HIGH: 50000

DEFAULT_DATABASES:
  "chembl_34": "ChEMBL 34"
  "drugbank_5": "DrugBank 5"
  "eXplore_diverse_2024": "eXplore Diverse 2024"
  "chemriya": "CHEMRIYA 1.2"
  "GDB17": "GDB17"
  "pubchem_2024": "PubChem 2024"
  "SureChEMBL_2024": "SureChEMBL 2024"
  "zinc22": "ZINC22"
  "chebi": "ChEBI"
  "coconut": "COCONUT"
  "foodb_2024": "FooDB"
  "lotus": "LOTUS 2021"
  "synple4": "Synple Chem 4"
  "mcule": "Mcule 2024"

MOLECULAR_PROPERTIES:
  - "MolecularWeight"
  - "NumLipinskiHBD"
  - "NumLipinskiHBA"
  - "TotalPolarSurfaceArea"
  - "NumRotatableBonds"
  - "FractionCSP3"
  - "NumAromaticRings"
  - "LogP"